### PR TITLE
Test against Optuna v2

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
The test failure is not related to Optuna and will be fixed in https://github.com/cupy/cupy/pull/3846

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins failures seem unrelated to this PR. LGTM.

**Pull request merged**
