### PR TITLE
CuPy v10 requires CUDA 10.0 or later

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Jenkins failure will be fixed in #658

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Test passed 😄

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I just merged another PR so let me retest to be safe 🙇‍♂️

**Pull request merged**
