### PR TITLE
fix seq2seq test to run validation code

### PR DESCRIPTION
**Pull request by kmaehashi**
Validation path of seq2seq example was not tested.
https://github.com/chainer/chainer/pull/4087#commitcomment-26328157

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins failure will be fixed by merging
https://github.com/chainer/chainer/pull/4117

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by unnonouno** [comment]
LGTM

**Comment by kmaehashi** [comment]
I noticed that `--validation-interval` was not backported to v3 branch...

**Pull request merged**
