### PR TITLE
Improve portability of shuffle test

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by okuta** [comment]
LGTM!
jenkins, test this please.

**Comment by okuta** [comment]
@toslunar Please check test result.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Fixed!

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
