### PR TITLE
Support cub on Ubuntu 16

### PR DESCRIPTION
**Pull request by kmaehashi**
See https://github.com/cupy/cupy/issues/2634#issuecomment-577116847

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by niboshi** [comment]
```
12:27:08 --- Shuffle Parameters ---
12:27:08 numpy: 1.17
12:27:08 scipy: 1.0
12:27:08 base: ubuntu16_py37-pyenv
12:27:08 cuda_cudnn_nccl: ('cuda92', 'cudnn73-cuda92', 'nccl2.3-cuda9')
12:27:08 --- Configuration ---
12:27:08 nccl: nccl2.3-cuda9
12:27:08 cudnn: cudnn73-cuda92
12:27:08 base: ubuntu16_py37-pyenv
12:27:08 requires: ['numpy<1.18', 'scipy<1.1']
12:27:08 cuda: cuda92
:
12:28:19 E: Unable to locate package gcc-7
```

**Comment by emcastillo** [comment]
seems it needs some custom ppa
https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5

**Comment by asi1024** [comment]
note: cupy/cupy#3097 may block this PR.

**Comment by leofang** [comment]
cupy/cupy#3097 is resolved. 

Looks like the PPA is indeed needed for installing gcc-6 and above...
https://askubuntu.com/questions/746369/how-can-i-install-and-use-gcc-6-on-xenial

**Comment by leofang** [comment]
btw I think gcc 7 is too new for CUDA 9.2.

**Comment by leofang** [comment]
@kmaehashi is there something I could help with this PR?

**Pull request closed without merging**
