### PR TITLE
Do not test against Python 2 / 3.4 for master branch

### LINKED ISSUE #490: Separate parameter combinations between master and stable
master and stable branches have separate requirements.
We should define the parameters separately.

### PR DESCRIPTION
**Pull request by kmaehashi**
Closes #490

Merge after Py2 drop in `master` branch (i.e. after releasing v7.0.0b3)

### CODE REVIEW

**Comment by emcastillo** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Some numpy-scipy version issues

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
NCCL_ERROR  🤔

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Please Fix CIs

**Comment by kmaehashi** [comment]
Sorry for taking time, I'm still unable to reproduce `NCCL_ERROR_UNHANDLED_CUDA_ERROR: unhandled cuda error` locally. Will try reproducing it on Jenkins interactively.
Jenkins test this please.

**Comment by leofang** [comment]
Hi, was directed to here from cupy/cupy#1941 to see if a pair of fresh eyes help. Just throwing some random thoughts (no experience with this error):
1. Any chance Chainer is doing multi-threading on top of `multiprocessing`? According to NCCL release note [(see here)](https://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/rel_2-2-12.html#rel_2-2-12):
> Using multiple processes in conjunction with multiple threads to manage the different GPUs may in some cases cause `ncclCommInitRank` to fail while establishing IPCs (cudaIpcOpenMemHandle). This problem does not appear when using only processes or only threads. This issue is fixed in recent driver versions, therefore, consider updating to the latest drive
>
2. Based on 1, it could also be that the driver/NCCL version in the Jenkins test is too old?
3. How about adding `–shm-size=1g –ulimit memlock=-1` to `nvidia-docker run`? It's recommended [in NCCL's doc](https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/troubleshooting.html#sharing-data).
4. A broken GPU could cause `ncclCommInitRank` to raise `ncclUnhandledCudaError`: https://github.com/pytorch/pytorch/issues/11756.

**Comment by leofang** [comment]
can this be related to chainer/chainer#7511?

**Comment by emcastillo** [comment]
I don't think it is, @kmaehashi was able to reproduce the bug locally so we will know soon :).
It sounds mostly like some kind of environment misconfiguration.

**Comment by leofang** [comment]
Cool!

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by beam2d** [comment]
If fixing the failure is difficult for now, how about skipping the test case for the newly added configuration as a tentative workaround? This change affects a wide range of development and, IMHO, making them proceed quickly should have higher priority than fixing the failure cleanly.

**Comment by toslunar** [comment]
How about giving a lucky id to Jenkins?
```
./run_combination_test.py --id 1
```
The current id (`1`) is lucky but becomes unlucky after the PR.  FYI, the last `daily_master_chainer-shuffled` passes with 10 combinations out of 21.

**Comment by niboshi** [comment]
What's the status?
It should not be difficult to skip affected tests as suggested by @beam2d.

**Comment by kmaehashi** [comment]
Changed the test variation as suggested by @toslunar to avoid this situation (until we migrate Jenkins to new test infrastructure).
pfnCI, test this please.

**Comment by kmaehashi** [comment]
I'll test separately to find the proper combination that can pass the test.

**Comment by kmaehashi** [comment]
pfnCI, test this please.
(`--id 4` passed the test)

**Comment by emcastillo** [comment]
Unlucky id 😂

**Comment by kmaehashi** [comment]
Ah, sorry configuration was not updated correctly...
pfnCI, test this please.

**Comment by kmaehashi** [comment]
The failure is not related to this PR (will be fixed in #532).

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Pull request merged**
