### PR TITLE
NCCL2

### PR DESCRIPTION
**Pull request by unnonouno**
I added a test case that checks NCCL2.

### CODE REVIEW

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by kmaehashi** [comment]
CentOS 6: failed...

```
./run_multi_test.py --base centos6_py2 --cuda cuda80 --cudnn cudnn7-cuda8 --nccl nccl2.0.5-cuda8 --numpy 1.12 --type gpu
```

```
[user@14591358e902 work]$ python
Python 2.7.13 (default, Oct 24 2017, 09:21:43) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy.cuda.nccl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/cuda/lib64/libnccl.so.2)
```

**Comment by kmaehashi** [comment]
In `docker.py`,

* NCCL choices needs to be updated.

```
nccl_choices = ['none', 'nccl1.3.4', 'nccl2.0.5-cuda8', 'nccl2.0.5-cuda9']
```

* CentOS 6/7 does not have `xz` command, so add `yum install xz`.  It is needed via tar (to expand deb).

**Comment by kmaehashi** [comment]
In CentOS 6, none of the following work.

* NCCL 2 for Ubuntu 16.04 (in this PR)
* NCCL 2 for Ubuntu 14.04
* NCCL 2 (O/S agnostic, manually copied)

Note: NCCL is already excluded for CentOS 6 from shuffle combination.
https://github.com/chainer/chainer-test/blob/master/shuffle.py#L27-L33

**Comment by unnonouno** [comment]
I update the PR
- Explicitly restricted version combination of CUDA, cuDNN and NCCL
- Skip nccl test for CentOS6
- Install xz for ubuntu14 and centos7

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by kmaehashi** [comment]
Could you please confirm and merge https://github.com/unnonouno/chainer-test/pull/1?
LGTM otherwise!

**Comment by kmaehashi** [comment]
Jenkins test this please

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
