### PR TITLE
Require Python 3.6+ for cupy master

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
TODO: Fix https://github.com/chainer/chainer-test/blob/3a19018f149a1f7e77d74c15bf0c33ee691cb63f/run_cupy_install_test.py#L44

**Comment by toslunar** [comment]
> TODO: Fix
> 
> https://github.com/chainer/chainer-test/blob/3a19018f149a1f7e77d74c15bf0c33ee691cb63f/run_cupy_install_test.py#L44

I suppose it can be fixed in a new PR.

Before https://jenkins.preferred.jp/job/chainer/job/cupy_master_cupy-install/375, "cupy install" test on Jenkins was failing because
```
08:22:55 + python setup.py -q sdist --cupy-no-cuda
08:22:56 
08:22:56     The folder cupy/core/include/cupy/cub/ is a git submodule but is
08:22:56     currently empty. Please use the command
08:22:56 
08:22:56         git submodule update --init
08:22:56 
08:22:56     to populate the folder before building from source.
```
https://jenkins.preferred.jp/job/chainer/job/cupy_master_cupy-install/374/ID=0,label=mn1-p100/console

**Comment by emcastillo** [comment]
LGTM, test failure is unrelated, we need to bump version for cupy install too.

**Pull request merged**
