### PR TITLE
pytest

### PR DESCRIPTION
**Pull request by niboshi**
Move to pytest.

Currently tests for chainer only.
Needed for https://github.com/chainer/chainer/pull/3324.

### CODE REVIEW

**Comment by unnonouno** [comment]
In my experiments, multi-process is less efficient than single-process. I recommend to use single process.

**Comment by niboshi** [comment]
I put `-n4` simply because there were `--processes=4`. Maybe it should be fixed in another PR, too?

**Comment by niboshi** [comment]
Rebased.

**Comment by mitmul** [comment]
LGTM

**Pull request merged**
