### PR TITLE
Update scipy version

### PR DESCRIPTION
**Pull request by toslunar**
- Takeover #600.
- Require SciPy 1.4+ in CuPy v9 tests.
- Add SciPy 1.6.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Review by emcastillo — APPROVED** [review]

**Pull request merged**
