### PR TITLE
Avoid setuptools 50

### PR DESCRIPTION
**Pull request by kmaehashi**
Supersedes https://github.com/chainer/chainer-test/pull/602

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by emcastillo — APPROVED** [review]
lgtm

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by toslunar** [comment]
It's possible that this line should be fixed instead.
https://github.com/chainer/chainer-test/blob/3726a807e1576ca169b4e7183f3b73816e76d845/docker.py#L859

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
The cause of scipy installation failure seems that that `setuptools` is included in `scipy`'s requiremen so the latest setuptools is installed when doing `pip install -U scipy`.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
