### PR TITLE
Fix cutensor for CUDA 11.1

### PR DESCRIPTION
**Pull request by emcastillo**
Missing definition

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by emcastillo** [comment]
errors should be fixed by https://github.com/cupy/cupy/pull/4276

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
The failure `test=cupy-install` is irrelevant.

@kmaehashi Could you review that the version numbers are correct?

**Review by toslunar — APPROVED** [review]
LGTM

**Comment by toslunar** [comment]
```
01:11:41 Step 30/35 : RUN eval $CUTENSOR_INSTALL && install_cutensor 1.2.0.2 1.2.0 11.1;
01:11:41  ---> Running in 3b8aa378adf3
01:11:41 Selecting previously unselected package libcutensor1.
01:11:41 (Reading database ... 17399 files and directories currently installed.)
01:11:41 Preparing to unpack libcutensor1_1.2.0.2-1_amd64.deb ...
01:11:41 Unpacking libcutensor1 (1.2.0.2-1) ...
01:11:41 Setting up libcutensor1 (1.2.0.2-1) ...
01:11:41 update-alternatives: using /usr/lib/x86_64-linux-gnu/libcutensor/11.0/libcutensor.so.1.2.0 to provide /usr/lib/x86_64-linux-gnu/libcutensor.so.1.2.0 (libcutensor.so.1.2.0) in auto mode
01:11:41 update-alternatives: using /usr/lib/x86_64-linux-gnu/libcutensor.so.1.2.0 to provide /usr/lib/x86_64-linux-gnu/libcutensor.so.1 (libcutensor.so.1) in auto mode
01:11:41 Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
01:11:41 Selecting previously unselected package libcutensor-dev.
01:11:41 (Reading database ... 17411 files and directories currently installed.)
01:11:41 Preparing to unpack libcutensor-dev_1.2.0.2-1_amd64.deb ...
01:11:41 Unpacking libcutensor-dev (1.2.0.2-1) ...
01:11:41 Setting up libcutensor-dev (1.2.0.2-1) ...
01:11:41 update-alternatives: using /usr/lib/x86_64-linux-gnu/libcutensor/11.0/libcutensor_static.a to provide /usr/lib/x86_64-linux-gnu/libcutensor_static.a (libcutensor_static.a) in auto mode
01:11:41 Processing triggers for libc-bin (2.27-3ubuntu1.3) ...
01:11:41 update-alternatives: error: alternative /usr/lib/x86_64-linux-gnu/libcutensor/11.1/libcutensor.so.1.2.0 for libcutensor.so.1.2.0 not registered; not setting
```
https://jenkins.preferred.jp/job/chainer/job/daily_master_cupy-shuffled/388/ID=3,label=mn1-p100/console

**Pull request merged**
