### PR TITLE
Run tests against NumPy 1.16

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Test failures are not related to this PR.

**Comment by kmaehashi** [comment]
Thanks, fixed.

**Comment by toslunar** [comment]
```
    elif args.numpy == '1.16':
        conf['requires'].append('numpy<1.17')
```

**Comment by toslunar** [comment]
Jenkins, test this please.

**Pull request merged**
