### PR TITLE
Cut protobuf 2

### PR DESCRIPTION
**Pull request by beam2d**

### CODE REVIEW

**Comment by gwtnb** [comment]
To cut protobuf 2, we have to edit some other lines. For example, https://github.com/pfnet/chainer-test/blob/_v2/run_test.py#L61

**Comment by unnonouno** [comment]
I updated this PR

**Comment by kmaehashi** [comment]
protobuf 2 support has dropped in Chainer v2.0 https://github.com/chainer/chainer/pull/3090

**Comment by niboshi** [comment]
Jenkins, test this please

**Pull request merged**
