### PR TITLE
Use gcc-6

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Using gcc-6 as it seems cub can be built with that.

**Comment by kmaehashi** [comment]
Updated Jenkins configuration `chainer_test_pr` (combinations `chainer-*`) to test CuPy v7 + Chainer v7, instead of CuPy v8 + Chainer v7.

pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
@asi1024 Test passed, PTAL :bow:

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
