### PR TITLE
SciPy 1.4

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Took a quick look in the `cupy-py35` log --- why is SciPy built from source instead of installing its wheel?

**Comment by leofang** [comment]
> scipy/fft/_pocketfft/pypocketfft.cxx:15:10: fatal error: pybind11/pybind11.h: No such file or directory

pybind11 is a dependency to build SciPy's new pocketfft.

**Comment by toslunar** [comment]
`cupy-py3-cutensor` and `cupy-py3-cub` configs are tested without SciPy.  Now it looks good to add the newest SciPy to plain `cupy-py3`, whose base is ubuntu18.

**Comment by toslunar** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
The result https://jenkins.preferred.jp/job/chainer/job/chainer-test_pr/152/label=mn1-p100,test=cupy-py35/console looks good because there's no skipped test in `tests/cupyx_tests/scipy_tests/special_tests/test_erf.py`.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by toslunar** [comment]
Let's postpone adding scipy 1.4 to the combination tests.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM!

**Comment by leofang** [comment]
Thank you!

**Pull request merged**
