### PR TITLE
Fix setting of coverage

### PR DESCRIPTION
**Pull request by okuta**
Current result of coveralls includes unnecessary reports.
Please see https://coveralls.io/builds/13862167

### CODE REVIEW

**Comment by kmaehashi** [comment]
This is duplicate of https://github.com/chainer/chainer-test/pull/347/files. Please merge that?

**Comment by niboshi** [comment]
Don't we need to specify like `--cov=chainer`, as in documentation?  https://pypi.python.org/pypi/pytest-cov

**Comment by unnonouno** [comment]
I think it is better to modify `setup.cfg` to add option for pytest.

**Comment by niboshi** [comment]
If added to `setup.cfg`, it also affects invocation from command line. That's not what we want.
(I think `--maxfail=2` and `--showlocal` should not be in `setup.cfg`, too)

**Comment by okuta** [comment]
OK, I close this PR.

**Pull request closed without merging**
