### PR TITLE
Update CuPy v9 requirements

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by toslunar** [comment]
So, I wasn't lucky enough to pass all the `id`s in
```
if [ ${test} = chainer-combination ]; then
  ./run_combination_test.py --id 4
elif [ ${test} = cupy-combination ]; then
  ./run_cupy_combination_test.py --id 3
elif [ ${test} = chainer-install ]; then
  ./run_install_test.py --id 1
elif [ ${test} = cupy-install ]; then
  ./run_cupy_install_test.py --id 1
else
  ./run_test.py --test ${test}
fi
```

**Comment by toslunar** [comment]
#570 seems related.

Jenkins, test this please.

**Comment by toslunar** [comment]
I changed the Jenkins config to
```
elif [ ${test} = cupy-install ]; then
  ./run_cupy_install_test.py --id 2 || ./run_cupy_install_test.py --id 3 || ./run_cupy_install_test.py --id 4
```

Jenkins, test this please.

**Pull request merged**
