### PR TITLE
Fix combination test

### PR DESCRIPTION
**Pull request by emcastillo**

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by toslunar — APPROVED** [review]
- NumPy >= 1.16: CuPy follows NEP-29.
- CUDA >= 9, != 9.1: https://github.com/cupy/cupy/pull/3670

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
