### PR TITLE
Move common requirements

### PR DESCRIPTION
**Pull request by toslunar**
#530 and #531.

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The PR requires https://github.com/cupy/cupy/pull/4325 and https://github.com/chainer/chainer/pull/8585.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
> The PR requires [cupy/cupy#4325](https://github.com/cupy/cupy/pull/4325) and [chainer/chainer#8585](https://github.com/chainer/chainer/pull/8585).

and their backports.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
