### PR TITLE
Drop NumPy<1.15 for CuPy v8

### LINKED ISSUE #552: Drop NumPy<1.15 for CuPy v8
https://github.com/cupy/cupy/pull/2938#issuecomment-577491597

### PR DESCRIPTION
**Pull request by niboshi**
Fixes  #552

### CODE REVIEW

**Comment by niboshi** [comment]
Rel:  https://github.com/cupy/cupy/pull/2938

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Seems like python 3.5 is getting cupy from elsewhere
```
10:32:04 Obtaining file:///work/cupy
10:32:08 Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from cupy==7.0.0) (1.9.3)
```

**Comment by emcastillo** [comment]
its getting it from the actual cupy requirements

**Pull request merged**
