### PR TITLE
Update versions in run_test.py

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by emcastillo** [comment]
Jenkins, test this please

**Review by emcastillo — APPROVED** [review]

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Seems like read the docs uses py3.6 and scipy 1.6 is only available from py3.7 :(
https://pypi.org/project/scipy/#files

**Comment by toslunar** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
```
 WARNING: The wheel package is not available.
14:18:14     ERROR: 'pip wheel' requires the 'wheel' package. To fix this, run: pip install wheel
14:18:14     Traceback (most recent call last):
14:18:14       File "/opt/pyenv/versions/3.8.0/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
14:18:14         subprocess.check_call(cmd)
14:18:14       File "/opt/pyenv/versions/3.8.0/lib/python3.8/subprocess.py", line 364, in check_call
14:18:14         raise CalledProcessError(retcode, cmd)
```
Seems that the docker image lacks a package?

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
