### PR TITLE
Test with Python 3.7

### PR DESCRIPTION
**Pull request by kmaehashi**
Will rebase after #438 got merged.

### CODE REVIEW

**Comment by toslunar** [comment]
Please rebase.

**Comment by kmaehashi** [comment]
Rebased.
Jenkins, test this please.

**Comment by toslunar** [comment]
chainer/chainer#5514

**Comment by kmaehashi** [comment]
Above PR merged.
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Note: ideep does not support Python 3.7 so far.

**Comment by kmaehashi** [comment]
Test failures are not related to this PR.

**Comment by beam2d** [comment]
LGTM

**Pull request merged**
