### PR TITLE
Remove flake8 check to reduce test time

### PR DESCRIPTION
**Pull request by okuta**
We can execute flake8 check without docker.

### CODE REVIEW

**Comment by delta2323** [comment]
I would like to know why it is safe to remove flake8 just for confirmation. Is it because we already check  flake8 violation in Travis?

**Comment by okuta** [comment]
Yes, we already do in Travis.

**Comment by delta2323** [comment]
I am curious how much we can reduce the test time.

**Comment by okuta** [comment]
The max 10 seconds in each test case.

**Pull request merged**
