### PR TITLE
Add CUDA 11.0

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Jenkins tests seem to fail for several reasons.
- [ ] `tests.cupy_tests.cuda_tests.test_nccl`: Failes to install nccl?
- [ ] `tests.cupy_tests.test_cudnn.*` : CuDNNError`: cuDNN Error: CUDNN_STATUS_NOT_SUPPORTED
- [ ] `tests.cupy_tests.core_tests.test_ndarray_elementwise_op.TestArrayElementwiseOp.test_doubly_broadcasted_pow`: Toleraces are too tight.
- [ ] `tests.cupy_tests.fft_tests.test_fft.TestMultiGpu*`: CUFFT_EXEC_FAILED
- [ ] `tests.cupyx_tests.scipy_tests.fft_tests.test_fft.Test?fft*`: Return values are totally different.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Great, now we are left with CNN and multi-GPU FFT.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
