### PR TITLE
only measure coverage for package being tested

### PR DESCRIPTION
**Pull request by kmaehashi**
After migrating to pytest, our coverage measurement includes sources outside of our package.

### CODE REVIEW

**Comment by unnonouno** [comment]
How about fixing configuration file such as `setup.cfg`?

**Comment by kmaehashi** [comment]
Appending such configuration to `.coveragerc` seems possible. I'll try that.
https://github.com/chainer/chainer/blob/master/.coveragerc#L1-L4

BTW, why do we need to omit protobuf from coverage? (https://github.com/chainer/chainer/pull/407, https://github.com/chainer/chainer/pull/1096)

Also need to remove Cython from .coveragerc (it was for CuPy).

Note: appending `--cov` to [setup.cfg](https://github.com/chainer/chainer/blob/master/setup.cfg#L10) introduces another dependency (`pytest-cov` package) for users just want to run Chainer unit test without coverage.

**Comment by okuta** [comment]
Please edit `.coveragerc`?

**Comment by okuta** [comment]
`caffe_pb2.py` and `caffe_pb3.py` are generated by automatically. We do not need these coverage information

**Comment by kmaehashi** [comment]
Thanks for the response.

I sent PR to chainer. https://github.com/chainer/chainer/pull/3684.
coveragerc in CuPy seems OK. https://github.com/cupy/cupy/blob/master/.coveragerc

**Comment by okuta** [comment]
OK thanks!

**Pull request closed without merging**
