### PR TITLE
Support NumPy 1.13 again

### PR DESCRIPTION
**Pull request by okuta**
I resend #273

### CODE REVIEW

**Comment by unnonouno** [comment]
This will be merged after https://github.com/cupy/cupy/pull/393

**Comment by okuta** [comment]
I merged cupy/cupy#393 .
Cloud you merge this?

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by okuta** [comment]
Please merge #21 before this PR.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by okuta** [comment]
We will use #299

**Pull request closed without merging**
