### PR TITLE
Support NumPy 1.15

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
blocked by https://github.com/cupy/cupy/pull/1702

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
The last blocker is chainer/chainer#5491.

**Comment by kmaehashi** [comment]
LGTM!

**Pull request merged**
