### PR TITLE
Use default gcc in ubuntu16

### PR DESCRIPTION
**Pull request by unnonouno**
Ubuntu16.04 is supported in CUDA.

### CODE REVIEW

**Comment by gwtnb** [comment]
This PR seems okay if we never test with CUDA 7.5 or earlier on Ubuntu 16.04.

**Comment by gwtnb** [comment]
`run_combination_test.py` may fail.

**Comment by unnonouno** [comment]
oh

**Comment by kmaehashi** [comment]
Took over. See #524

**Pull request closed without merging**
