### PR TITLE
Use newer version of protobuf/numpy for Python 3.7 test

### PR DESCRIPTION
**Pull request by kmaehashi**
* protobuf 3.3.0 cannot be built against Python 3.7. As `protobuf` now provides wheel package, which is using C++ implementation, it is not much meaningful to test with protobuf built from source.
* NumPy 1.14.4 is the first version that supports Python 3.7.
  https://github.com/numpy/numpy/blob/master/doc/release/1.14.4-notes.rst

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
I locally confirmed `chainer-py3` and `cupy-py3` works.
To pass the test, https://github.com/chainer/chainer/pull/5572 and https://github.com/cupy/cupy/pull/1743 needs to be merged.

**Comment by beam2d** [comment]
OK, will check them.

**Comment by beam2d** [comment]
CI not passed due to cyclic dependencies between this and https://github.com/chainer/chainer/pull/5572 and https://github.com/cupy/cupy/pull/1743. I'm going to merge them without CI pass and will see if they pass the merge test...

**Pull request merged**
