### PR TITLE
Use cuTENSOR 1.2

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
The Jenkins failure of tests of cupyx.scipy.ndimage.morphology is unrelated to this PR.
LGTM.

**Comment by asi1024** [comment]
LGTM!

**Pull request merged**
