### PR TITLE
Support cuTENSOR 1.3.3

### PR DESCRIPTION
**Pull request by takagi**

### CODE REVIEW

**Comment by takagi** [comment]
BTW, how about adding new combinations only for major/minor updates instead of every patch update?

**Comment by kmaehashi** [comment]
That sounds good, I think it's ok to only define a combination for the latest patch release (i.e., the latest in 1.3.x series) that matches with the libray_installer.

**Comment by takagi** [comment]
Defer changes before cuTENSOR 1.3.3 that comes soon.

**Comment by kmaehashi** [comment]
pfnCI, run Jenkins please.

**Review by kmaehashi — APPROVED** [review]

**Pull request merged**
