### PR TITLE
Enable tests of CUB backend

### PR DESCRIPTION
**Pull request by asi1024**
Another PR to test CUB block reduction
ref: #577.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Jenkins failure seems unrelated.

**Comment by kmaehashi** [comment]
LGTM!

**Comment by leofang** [comment]
Thanks a lot, @asi1024 @kmaehashi 🎊

**Pull request merged**
