### PR TITLE
NCCL v2.10.3

### PR DESCRIPTION
**Pull request by takagi**
We can test NCCL v2.10 with CUDA 11.4 in FlexCI.

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Review by kmaehashi — APPROVED** [review]

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by takagi** [comment]
pfnCI, test this please.

**Pull request merged**
