### PR TITLE
Test with SciPy 1.0

### PR DESCRIPTION
**Pull request by toslunar**

### CODE REVIEW

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
chainer/chainer#5496 is probably blocking this PR.

**Comment by toslunar** [comment]
Added SciPy 0.19 to shuffle test since #444 is closed.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
```
+ ./run_combination_test.py --id 1
--- Shuffle Parameters ---
protobuf: 3
cuda_cudnn_nccl: ('cuda80', 'none', 'nccl1.3')
ideep: 2.0
scipy: None
base: ubuntu16_py36-pyenv
h5py: 2.5
theano: 0.8
numpy: 1.13
pillow: 3.4
--- Configuration ---
nccl: nccl1.3
cudnn: none
base: ubuntu16_py36-pyenv
requires: ['numpy<1.14', 'h5py<2.6', 'theano<0.9', 'protobuf<4', 'ideep4py<2.1', 'pillow<3.5']
cuda: cuda80
sha256:a8058b1e5a966f9e473e00d9005dda6d7fe0ac934f27d5c5284647c4e9b73e7b
```
```
RuntimeError: iDeep is not available.
Reason: ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

Ensure iDeep requirements are satisfied: https://github.com/intel/ideep
```

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
LGTM! Test failures are not related to this PR.

**Pull request merged**
