### PR TITLE
Extend timeout for combination tests

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by kmaehashi** [comment]
The combination test took 2.5 hours, so the timeout seems reasonable. The following tests seems flaky.

```
13:49:19 FAILED cupyx_tests/scipy_tests/fft_tests/test_fft.py::TestRfft_param_155_{axis=0, n=15, norm='forward', shape=(10, 10)}::test_irfft
13:49:19 FAILED cupyx_tests/scipy_tests/fft_tests/test_fft.py::TestRfft_param_155_{axis=0, n=15, norm='forward', shape=(10, 10)}::test_irfft_backend
13:49:19 FAILED cupyx_tests/scipy_tests/fft_tests/test_fft.py::TestRfft_param_155_{axis=0, n=15, norm='forward', shape=(10, 10)}::test_irfft_overwrite
13:49:19 FAILED cupyx_tests/scipy_tests/fft_tests/test_fft.py::TestRfft_param_155_{axis=0, n=15, norm='forward', shape=(10, 10)}::test_irfft_overwrite_plan
13:49:19 FAILED cupyx_tests/scipy_tests/fft_tests/test_fft.py::TestRfft_param_155_{axis=0, n=15, norm='forward', shape=(10, 10)}::test_irfft_plan
```

pfnCI, test this please.

**Comment by leofang** [comment]
> The following tests seems flaky.

I think those are due to precision issue, possibly involving certain SciPy/CUDA versions.

**Comment by emcastillo** [comment]
Yes, looks like tolerance, but these tests failed in the same run. Let me run them again.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
I will merge this and send a followup pr for the flaky tests in cupy repo

**Pull request merged**
