### PR TITLE
Use CUDA 10.1 update 2

### PR DESCRIPTION
**Pull request by kmaehashi**
This PR also removes `cuda*_driver` which is no longer be used.

### CODE REVIEW

**Comment by hvy** [comment]
Jenkins, test this please.

**Comment by hvy** [comment]
I can't really tell but do you know if the numerical error are related to this update?

**Comment by kmaehashi** [comment]
Raised another issue to work on supporting Update 2: https://github.com/cupy/cupy/issues/2569

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
