### PR TITLE
Test with NumPy 1.14

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
Travis failure should be solved via https://github.com/chainer/chainer-test/pull/426

**Comment by unnonouno** [comment]
please rebase the master

**Comment by kmaehashi** [comment]
Rebased.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
st: test-and-merge

**Pull request merged**
