### PR TITLE
Run more examples in cupy-example tests

### LINKED ISSUE #647: Test more examples in cupy-example test

### PR DESCRIPTION
**Pull request by asi1024**
Resolve #647.

~Depends on https://github.com/cupy/cupy/pull/4999.~

### CODE REVIEW

**Comment by kmaehashi** [comment]
Blocked by https://github.com/cupy/cupy/pull/4999

**Comment by asi1024** [comment]
https://github.com/cupy/cupy/pull/4999 has merged.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Fixed to set `PYTHONPATH`.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
