### PR TITLE
Rename `CUPY_BACKENDS` to `CUPY_ACCELERATORS`

### PR DESCRIPTION
**Pull request by asi1024**
For https://github.com/cupy/cupy/pull/3461.

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by leofang** [comment]
It's odd, the `--recursive` argument in `git clone` is gone... why doesn't the main repo see this error?

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by leofang** [comment]
Maybe https://github.com/cupy/cupy/pull/3572 can fix the error in `cupy-install`?

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
CuPy build timed-out... (currently limited to 20m)

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
chainer-example failure seems a temporary network issue of the dataset server.

**Pull request merged**
