### PR TITLE
Use NumPy 1.19 in v7

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
The backports of https://github.com/cupy/cupy/pull/3498, https://github.com/cupy/cupy/pull/3499 and https://github.com/cupy/cupy/pull/3502 will be needed?

**Comment by kmaehashi** [comment]
Discussion: https://github.com/cupy/cupy/issues/3406#issuecomment-673715890

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
LGTM.

**Pull request merged**
