### PR TITLE
Use pip for installing Chainer/CuPy

### PR DESCRIPTION
**Pull request by niboshi**
Fixes chainer/chainer#7084

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by toslunar** [comment]
Jenkins, test this please.

**Comment by niboshi** [comment]
Should it be done in this PR?
If so, I want to add `-v` to all the "pip install" instances in this repository.

**Comment by toslunar** [comment]
To me, `pip install -v` looks closer to `python setup.py` than `pip install`, while I don't have a good reference.

Is there a reason why `pip install` and `python setup.py` were mixed?  If you are somewhat confident that the answer is no, it's reasonable to use `pip install` without `-v` in the PR.

**Comment by niboshi** [comment]
I guess the reason was to test multiple ways of installation.
I'm pretty sure it was not for the amount of logs.

**Pull request merged**
