### PR TITLE
Limit coverage version to <5

### PR DESCRIPTION
**Pull request by niboshi**

### CODE REVIEW

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
@niboshi Could you fix `run_cupy_combination_test.py` too?
https://github.com/chainer/chainer-test/blob/5f12c6f5ba29bf8b479ed392c52cf7619ab6da54/run_cupy_combination_test.py#L60

**Comment by niboshi** [comment]
Thanks, force-pushed.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins, test this please.

**Comment by asi1024** [comment]
Jenkins test is [still failing](https://jenkins.preferred.jp/job/chainer/job/chainer-test_pr/83/) on cupy-doc test. scipy v1.4.0 released today may be related to this error.

**Comment by asi1024** [comment]
PR #547 resolved Jenkins failure. I will merge this PR because current failure is unrelated to this PR.

**Pull request merged**
