### PR TITLE
Add imagenet test with Nvidia DALI

### PR DESCRIPTION
**Pull request by takagi**
This PR adds a test for imagenet example with Nvidia DALI.

### CODE REVIEW

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
@takagi Please check test result.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
Please follow the change in chainer/chainer#6397 .

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
Please check test result.

**Comment by takagi** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
Now chainer/chainer#6397 is merged, I kicked Jenkins again.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by takagi** [comment]
Another error I've never seen. I will check it.

**Comment by takagi** [comment]
It looks that the size of test image that is not 256x256 is the reason of the error.

**Comment by takagi** [comment]
Jenkins, test this please.

**Comment by takagi** [comment]
This PR further requires https://github.com/chainer/chainer/pull/6462 for Python2, which is used in `--test=test_example`.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by toslunar** [comment]
The Jenkins failure
```
tests.chainer_tests.functions_tests.pooling_tests.test_average_pooling_nd.TestAveragePoolingND_param_6_{pad_value=None, dtype=<class 'numpy.float16'>, dims=(4, 3)}.test_double_backward_gpu_no_cudnn
```
is unrelated to the PR.

**Comment by toslunar** [comment]
The example in Chainer v5 does not support `--device=0`.

**Pull request merged**
