### PR TITLE
Fix NumPy/SciPy verion ranges

### PR DESCRIPTION
**Pull request by kmaehashi**

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by asi1024** [comment]
Should be fixed to numpy_upper_version = '1.17'.
https://github.com/chainer/chainer-test/blob/8446e70ecdbeda7112855f165f0840bb27904264/run_test.py#L348-L360
Anyway, how about fixing to `numpy_requires = 'numpy=={}'.format(numpy_min_version)` if it is intended to test with oldest supported NumPy's version?

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Pull request merged**
