### PR TITLE
[wip] Disable coverage

### PR DESCRIPTION
**Pull request by unnonouno**
I disabled coverage report

### CODE REVIEW

**Comment by niboshi** [comment]
I think this fixes https://github.com/chainer/chainer/issues/3173?

**Comment by unnonouno** [comment]
No i want to store coverage report actually because i found some critical problems from coverage reports. I thinks it is better to change integration behavior.
This fix aims to reduce test time.

**Comment by unnonouno** [comment]
jenkins test this please

**Comment by niboshi** [comment]
I see. Is it still WIP?

**Comment by unnonouno** [comment]
We can reduce test time with single process #309. And we can change threshold of coveralls integration. I'll close this PR.

**Pull request closed without merging**
