### PR TITLE
No editable install for cupy

### PR DESCRIPTION
**Pull request by kmaehashi**
It seems that `pip install --user -e` does not work if `pyproject.yaml` exists.
https://github.com/pypa/pip/issues/7953#issuecomment-618210657

### CODE REVIEW

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Blocked by https://github.com/cupy/cupy/pull/4685

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by kmaehashi** [comment]
Test failure seems unrelated (cupy-combination exits with 124 which is a timeout...)

**Comment by kmaehashi** [comment]
pfnCI, test this please.

**Comment by emcastillo** [comment]
Jenkins, test this please

**Comment by emcastillo** [comment]
Jenkins, test this please

**Pull request merged**
