### PR TITLE
Drop support for CUDA 7.0 / 7.5

### PR DESCRIPTION
**Pull request by kmaehashi**
* Remove `cuda70` and `cuda75`
* Remove `cudnn4`, `cudnn5`, `cudnn51`, `cudnn6` (for CUDA 7.x)
  (note that cuDNN v5+ with CUDA 8.x is still supported e.g., `cudnn5-cuda8`).

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
