### PR TITLE
Skip SGEMM test when it does not exist

### PR DESCRIPTION
**Pull request by unnonouno**
We need to skip SGEMM test for v1.

### CODE REVIEW

**Comment by takagi** [comment]
It may be better to move example tests to chainer and cupy repositories as `chainer/tests/example_tests` and `cupy/tests/example_tests`?

**Comment by unnonouno** [comment]
Hum, OK. It sounds good.

**Comment by takagi** [comment]
It would be good to merge this PR for now and I will make PRs to move tests later.

**Comment by unnonouno** [comment]
Ok, please merge this pr first.

**Comment by takagi** [comment]
LGTM!

**Pull request merged**
