### PR TITLE
Make html on test

### PR DESCRIPTION
**Pull request by unnonouno**
It is better to check if it can generates HTML.

### CODE REVIEW

**Comment by niboshi** [comment]
How about running `make clean` between them?

**Comment by niboshi** [comment]
LGTM

**Comment by niboshi** [comment]
Looks like `sphinx_rtd_theme` needs to be installed explicitly.

**Comment by niboshi** [comment]
LGTM

**Comment by unnonouno** [comment]
check it first: https://github.com/chainer/chainer/pull/3464

**Comment by niboshi** [comment]
jenkins, test this please

**Comment by niboshi** [comment]
LGTM!

**Pull request merged**
