### PR TITLE
Add test for text classification example

### PR DESCRIPTION
**Pull request by takagi**
This PR follows https://github.com/chainer/chainer/pull/5591 adding test for text classification example.

### CODE REVIEW

**Comment by kmaehashi** [comment]
Jenkins, test this please.

**Comment by kmaehashi** [comment]
Could you check jenkins error?

**Comment by takagi** [comment]
I modified the path of output files as well as added test mode for the example so that it can be tested with reasonable cost on CI. This PR and https://github.com/chainer/chainer/pull/5666 are now mutually dependent to merge to each master.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
jenkins, test this please.

**Comment by okuta** [comment]
LGTM!

**Pull request merged**
